version: '3'
services:
  postgres:
    container_name: toadstool_postgres_db
    image: postgres:10
    restart: always
    environment:
      POSTGRES_PASSWORD: toadstool
    volumes: 
      - ./db/postgres-init:/docker-entrypoint-initdb.d
    ports:  
      - 5432:5432
  sqlserver:
    container_name: toadstool_sqlserver_db
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Toadstool123
    ports:  
      - 1433:1433