version: '3'
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: toadstool
    volumes: 
      - ./test/postgres-init:/docker-entrypoint-initdb.d
    ports:  
      - 5432:5432
  sqlserver:
    image: mcr.microsoft.com/mssql/server:latest
    restart: always
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Toadstool123
    ports:  
      - 1433:1433